### ISSUE TITLE
Int64 Constructor accepts hex only, we need decimal or oct

### ISSUE THREAD

**Issue by DanielYWoo** [broofa/node-int64#15]
If you pass in a decimal 126 in string like this:

new Int64("126") 

The number will be 294.

**Comment by xsilen** [comment]
yes, we need decimal

**Comment by michielbdejong** [comment]
I ran into this same problem and ended up using https://www.npmjs.com/package/int64 - it just does the hex2dec and dec2hex part, but see https://github.com/michielbdejong/int64/blob/33b4f8e89b713805fc8b565dda90c2d79eee0355/README.md for how to go between hex strings and 8-byte Buffers.

**Comment by broofa** [comment]
![image](https://user-images.githubusercontent.com/164050/52737878-42886600-2f82-11e9-81de-c750db7b4ac3.png)
