### ISSUE TITLE
Is Int64.MAX_INT correct?

### ISSUE THREAD

**Issue by jeking3** [broofa/node-int64#20]
According to documentation, Number.MAX_SAFE_INTEGER is (2^53)-1, however in Int64 the definition of MAX_INT is (2^53).  Is that really correct?

**Comment by broofa** [comment]
It's "correct enough".  😸  (FWIW, MAX_SAFE_INTEGER wasn't a thing when I wrote this module.)

I'd fix it if I felt this module was worth maintaining, but now that [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)'s are thing, my plan is to deprecate this module.

**Comment by jeking3** [comment]
Thanks.  Work was just done to add `node-int64` to javascript, and then I found later on it does not allow for 64-bit integer math.  So I am recommending a move to `bignum` instead.

**Comment by broofa** [comment]
FWIW: https://issues.apache.org/jira/browse/THRIFT-4801
