### ISSUE TITLE
performance comparison: node-int64 vs BigInt; un-deprecate node-int64?

### ISSUE THREAD

**Issue by timotheecour** [broofa/node-int64#21]
in light of https://github.com/tc39/proposal-bigint/issues/117 I think there's a use case for node-int64 if BigInt is as slow as mentioned:

* performance of BigInt
> tl;dr An implementation of Longs on top of BigInts (with asIntN) in Scala.js is 60x slower than the existing one based on 32-bit integers.

* performance of a int64 implementation (in elm which can compile to js):
https://github.com/folkertdev/elm-int64 reports a 2x slowdown only for their implementation:
> Performance is roughly half for subtraction, addition and the bitwise operators. That is great considering int64 is really two 32-bit integers, so we're doing operations twice.

furthermore, BigInt isn't a replacement for int64/uint64 because of overflow/wrapping behavior that one may want to preserve when porting say a C program to js, which BigInt wouldn't allow (unless a wrapping layer is used which would further increase slowdown)

**Comment by broofa** [comment]
I don't have any time / energy / interest in maintaining this module.  I'd be willing to transfer ownership, but I'd need to be convinced the new owner could be trusted to maintain it responsibly.  (Nobody wants a repeat of the event-stream hack.)
