### ISSUE TITLE
String representation of the Int64 representation

### ISSUE THREAD

**Issue by jorgebay** [broofa/node-int64#6]
It would be nice to have the string representation of numbers bigger than `Math.pow(2, 53)` integrated on this module.

**Comment by soulne4ny** [comment]
Version 0.4.0:

```
$ node
> const Int64 = require( 'node-int64' );
> b = new Buffer([0xff, 0xee, 0xdd, 0xcc, 0xAA, 0xBB, 0x00, 0x99])
<Buffer ff ee dd cc aa bb 00 99>
> (new Int64( b )).toString(10);
'-4822678473342823'
> b = new Buffer([96, 0x8e, 0x9c, 0xc6, 0x83, 0xa5, 0x19, 0x56])
<Buffer 60 8e 9c c6 83 a5 19 56>
> (new Int64( b )).toString(10);
'Infinity'
```

**Comment by liaozhongwu** [comment]
Any update on this issue? I publish [hex2decimal](https://www.npmjs.com/package/hex2decimal) to solve this problem. #17

**Comment by soulne4ny** [comment]
`.toSignedDecimalString()` does correct transformation.
Then it is quite strange `toString()` can not do what it is supposed to do.

**Comment by michielbdejong** [comment]
If you want to convert between 8-byte buffers and decimal strings, you can also use https://github.com/q3boy/int64/pull/1/files
